# Generated by Django 6.0.2 on 2026-05-21 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Текст пресс-релиза')),
            ],
            options={
                'verbose_name': 'Пресс-релиз',
                'verbose_name_plural': 'Пресс-релизы',
                'ordering': ['-date'],
            },
        ),
    ]
