# Generated by Django 6.0.2 on 2026-05-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressReleaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Фотография')),
                ('press_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landing.pressrelease', verbose_name='Пресс-релиз')),
            ],
            options={
                'verbose_name': 'Фотография пресс-релиза',
                'verbose_name_plural': 'Фотографии пресс-релиза',
            },
        ),
    ]
